### ISSUE TITLE
Redmine/Chiliproject configuration

### ISSUE THREAD

**Issue by tommyblue** [stefanoverna/redpomo#1]
To let Redpomo correctly work with Redmine's (or Chiliproject's) time tracking, a default time tracking activity must be set in `http://REDMINE_PATH/enumerations` or the `redpomo push LOGFILE` call will fail with:

```
[~] redpomo push LOGFILE
~/.rvm/gems/ruby-1.9.3-p125/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!': 422 Unprocessable Entity (RestClient::UnprocessableEntity)
```

A valid alternative is to specify an `activity_id` param in the post request.

Both in my redmine and chiliproject installations the default time tracking activity wasn't set, I think this is the default

**Comment by stefanoverna** [comment]
Thanks @tommyblue, will look into it
